[package]
name = "libstuhfl-sys"
version = "0.1.0"
edition = "2021"
links = "stuhfl"
authors = ["Nathan Rowan <rvanathanrowan@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
bindgen = "0.60"

[features]
static = []